# Generated by Django 5.2.8 on 2025-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
